// JsonDemoData
// 20200718-230315-xxxx：电子工单提交/缓存的毫秒时间戳，为工单的唯一识别号。
{
  "20200718230315":[
    {
      "id":1,
      "ticket":"20200231CW_ML_01",
      "airport":"杭州机场"
    },
    {
      "id":2,
      "city":"上海",
      "airport":"浦东机场"
    },
    {
      "id":3,
      "city":"北京",
      "airport":"首都机场"
    },
    {
      "id":4,
      "city":"成都",
      "airport":"成都机场"
    },
    {
      "id":5,
      "city":"南京",
      "airport":"南京机场"
    },
    {
      "id":6,
      "city":"天津",
      "airport":"天津机场"
    }
  ]
}